# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 544)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.messageList = QtWidgets.QTextBrowser(self.centralwidget)
        self.messageList.setGeometry(QtCore.QRect(20, 50, 401, 411))
        self.messageList.setObjectName("messageList")
        self.messageText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.messageText.setGeometry(QtCore.QRect(20, 480, 311, 31))
        self.messageText.setObjectName("messageText")
        self.sendMessageButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendMessageButton.setGeometry(QtCore.QRect(344, 480, 81, 31))
        self.sendMessageButton.setObjectName("sendMessageButton")
        self.timerLabel = QtWidgets.QLabel(self.centralwidget)
        self.timerLabel.setGeometry(QtCore.QRect(356, 10, 61, 31))
        self.timerLabel.setText("")
        self.timerLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timerLabel.setObjectName("timerLabel")
        self.scoreLabel = QtWidgets.QLabel(self.centralwidget)
        self.scoreLabel.setGeometry(QtCore.QRect(150, 10, 61, 31))
        self.scoreLabel.setText("SCORE: 0")
        self.scoreLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.scoreLabel.setObjectName("scoreLabel")
        self.userNameLabel = QtWidgets.QLabel(self.centralwidget)
        self.userNameLabel.setGeometry(QtCore.QRect(30, 20, 221, 16))
        self.userNameLabel.setText("")
        self.userNameLabel.setObjectName("userNameLabel")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(20, 480, 401, 31))
        self.startButton.setObjectName("startButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        #self.sendMessageButton.clicked.connect(self.clickOnSendButton)
       # self.startButton.clicked.connect(self.clickOnStartButton)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.messageText.setPlaceholderText(_translate("MainWindow", "Enter message here"))
        self.sendMessageButton.setText(_translate("MainWindow", "SEND"))
        self.startButton.setText(_translate("MainWindow", "START"))
        self.startGame()

    def startGame(self):
        """События, которые должны произойти перед началом игры"""
        self.messageText.hide()
        self.sendMessageButton.hide()
        self.startButton.show()

    def clickOnStartButton(self):
        """Обработка нажатия на кнопку Начать игру"""
        self.messageText.show()
        self.sendMessageButton.show()
        self.startButton.hide()

    def allowSendingMessages(self):
        """Разрешить отправку сообщений, тк очередь данного пользователя"""
        self.messageText.setEnabled(True)
        self.sendMessageButton.setEnabled(True)
        pass

    def prohibitSendingMessages(self):
        """Запрет на отправку сообщений, тк очередь другого пользователя"""
        self.messageText.setEnabled(False)
        self.sendMessageButton.setEnabled(False)
        pass
