# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

class Ui_RegistrationWindow(object):
    def setupUi(self, RegistrationWindow):
        self.RegistrationWindow = RegistrationWindow
        self.RegistrationWindow.setObjectName("RegistrationWindow")
        self.RegistrationWindow.resize(351, 152)
        self.centralwidget = QtWidgets.QWidget(self.RegistrationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.enterNameButton = QtWidgets.QPushButton(self.centralwidget)
        self.enterNameButton.setGeometry(QtCore.QRect(20, 82, 311, 31))
        self.enterNameButton.setObjectName("enterNameButton")
        self.nameText = QtWidgets.QLineEdit(self.centralwidget)
        self.nameText.setGeometry(QtCore.QRect(20, 40, 311, 31))
        self.nameText.setObjectName("nameText")
        self.nameText.setText('')
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 311, 16))
        self.label.setObjectName("label")
        self.RegistrationWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self.RegistrationWindow)
        self.statusbar.setObjectName("statusbar")
        self.RegistrationWindow.setStatusBar(self.statusbar)

        self.retranslateUi()
        self.enterNameButton.clicked.connect(self.registerUser)
        QtCore.QMetaObject.connectSlotsByName(self.RegistrationWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.RegistrationWindow.setWindowTitle(_translate("RegistrationWindow", "MainWindow"))
        self.enterNameButton.setText(_translate("RegistrationWindow", "ENTER"))
        self.label.setText(_translate("RegistrationWindow", "Enter your name"))

    def registerUser(self):
        self.__username = self.nameText.text()
        if self.__username != "":
            self.RegistrationWindow.close()

    def getUsername(self):
        return self.__username
